spring.application.name=Assignment3CRUDAPI
spring.datasource.url=jdbc:postgresql://ep-silent-flower-ad0qgynx-pooler.c-2.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_dtlX8osxDS6w@ep

spring.jpa.hibernate.ddl-auto=update

# Logging (optional, helps for debugging)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE